name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run tests (rquery-orm-macros)
        run: |
          cd rquery-orm-macros
          cargo test --all-features --verbose
      - name: Run tests (rquery-orm)
        run: |
          cargo test --all-features --verbose
      - name: Install llvm-cov
        run: |
          rustup component add llvm-tools-preview
          cargo install cargo-llvm-cov
      - name: Coverage (rquery-orm-macros >= 85%)
        run: |
          cd rquery-orm-macros
          cargo llvm-cov --lib --tests --fail-under-lines 85

